### ISSUE TITLE
setup.py: Contains wrong URL parameter

### ISSUE THREAD

**Issue by jenisys** [ArneBachmann/rsyncr#5]
SEE ALSO:
* https://pypi.python.org/pypi/rsyncr/2018.1225.2424
* https://github.com/ArneBachmann/rsyncr/blob/master/setup.py#L37

SHOULD-BE:
```python
...
url = https://github.com/ArneBachmann/rsyncr
```

**Comment by ArneBachmann** [comment]
5f1425c6a9
